# Generated by Django 3.1.3 on 2020-12-14 12:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Aircraft',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aircraft_name', models.CharField(max_length=20)),
                ('aircraft_type', models.CharField(max_length=20)),
                ('aircraft_no', models.CharField(max_length=15)),
                ('aircraft_capacity', models.IntegerField()),
                ('date_created', models.DateField(null=True)),
                ('date_updated', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_employment', models.DateField(null=True)),
                ('role', models.CharField(max_length=200)),
                ('department', models.CharField(max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=500)),
                ('registration_number', models.CharField(max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_number', models.CharField(max_length=10)),
                ('take_off_location', models.CharField(max_length=50)),
                ('price', models.FloatField()),
                ('arrival_time', models.TimeField()),
                ('destination', models.CharField(max_length=50)),
                ('departure_date', models.DateField()),
                ('date_created', models.DateField(null=True)),
                ('date_updated', models.DateField(null=True)),
                ('aircraft', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='app.aircraft')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_reference', models.CharField(max_length=10)),
                ('flight_class', models.CharField(max_length=20)),
                ('seat_number', models.IntegerField()),
                ('price', models.FloatField()),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='app.flight')),
                ('passenger', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='app.passenger')),
            ],
        ),
    ]
